# Generated by Django 5.0.1 on 2024-02-01 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Наука', 'Наука'), ('Спорт', 'Спорт'), ('Искусство', 'Искусство')], max_length=100, verbose_name='Тема статьи')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название статьи')),
                ('summary', models.CharField(blank=True, max_length=1000, null=True, verbose_name='кратко о статье')),
                ('text', models.TextField(blank=True, max_length=10000000000000000, null=True, verbose_name='текст статьи')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата публикации статьи')),
                ('info', models.URLField(blank=True, verbose_name='Источник(и)')),
                ('author', models.CharField(max_length=1000, verbose_name='Автор')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Фото')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Sience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название статьи')),
                ('summary', models.CharField(blank=True, max_length=1000, null=True, verbose_name='кратко о статье')),
                ('text', models.TextField(blank=True, max_length=10000000000000000, null=True, verbose_name='текст статьи')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата публикации статьи')),
                ('info', models.URLField(blank=True, verbose_name='Источник(и)')),
                ('author', models.CharField(max_length=1000, verbose_name='Автор')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Фото')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название статьи')),
                ('summary', models.CharField(blank=True, max_length=1000, null=True, verbose_name='кратко о статье')),
                ('text', models.TextField(blank=True, max_length=10000000000000000, null=True, verbose_name='текст статьи')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата публикации статьи')),
                ('info', models.URLField(blank=True, verbose_name='Источник(и)')),
                ('author', models.CharField(max_length=1000, verbose_name='Автор')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Фото')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.topic')),
            ],
        ),
    ]
